config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show
  
  root 'posts#index'
  resources :posts do
    resources :comments
    resources :upvotes, only: :create
    resources :downvotes, only: :create
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  validates :post_id, :text, :user_id, presence: true
  
  delegate :name, to: :user, prefix: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  belongs_to :user
  has_many :comments
  mount_uploader :photo, PhotoUploader
  
  validates  :photo, :description, :user_id, presence: true
  
  delegate :photo, :name, to: :user, prefix: true
  
  acts_as_votable
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :posts
  has_many :comments
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  mount_uploader :photo, PhotoUploader
  
  acts_as_voter
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :name, :photo)}
     devise_parameter_sanitizer.permit(:sign_in) {|u| u.permit(:email, :password, :remember_me)}
     devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :photo)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :is_owner?, only: :destroy
  
  def create
    @post=Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
    if @comment.valid?
      redirect_to root_path
    else
      flash[:alert] = "Invalid Attributes"
      redirect_to root_path
    end
  end

def destroy
  @comment=Comment.find(params[:id])
  @comment.destroy
  redirect_to root_path
end

private
def is_owner?
  @comment=Comment.find(params[:id])
  if @comment.user! == current_user
    redirect_to root_path
  end
end



private
def comment_params
    params.require(:comment).permit(:text, :post_id)
end
end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController
  before_action :authenticate_user!

 def create
   @post=Post.find(params[:post_id])
   @post. downvote_from current_user
   
   
   respond_to do |format|
       format.html {redirect_to posts_path}
       format.js {}
   end

 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :is_owner?, only: [:edit, :update, :delete]
  
  
  def index
    @posts= Post.all.order('created_at DESC').includes(:user, comments: :user)
  end
  
  def show
    @post=Post.find(params[:id])
  end
  
  
  
  def new
    @post = Post.new(params[:id])
  end
  
  
  
  def create
    @post = current_user.posts.create(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  
  def edit
    @post= Post.find(params[:id])
  end
  
  def update
    @post= Post.find(params[:id])
    @post.update(post_params)
    if @post.valid?
      redirect_to root_path
    else
    render :edit, status: :unprocessable_entity
    end
  end
  
private
  def is_owner?
    if Post.find(params[:id]).user != current_user
      redirect_to root_path
    end
  end
  
  
  def destroy
    @post=Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end
  
  
  
  



private
  def post_params
    params.require(:post).permit(:photo, :description)
  end 
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :authenticate_user!

 def create
   @post=Post.find(params[:post_id])
   @post.liked_by current_user
   
   
   respond_to do |format|
       format.html {redirect_to posts_path}
       format.js {}
   end
       
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=Users.find(params[:id])
  
  end
  



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/downvotes/create.js.erb
$ ('#likes_container_<%= @post.id %>').html ("<%= escape_javascript render partial: '/posts/likes', locals: {post: @post} %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags  %>
</head>
<body>
  <nav>
    <div class= "row">
      <div class= "col-lg-10 col-lg-offset-1">
        <div class="row">
          <div class="wrapper">
            
            <div class="col-xs-5">
              <span class="pull-left brand"><%=link_to "Instapost",root_path%></span>
            </div>
            <div class="col-xs-6">
              <% if user_signed_in? %>
                <span class="nav_links pull-right"><%= link_to 'New Post', new_post_path %></span>
                <span class="nav_links pull-right"><%= link_to 'Edit Settings', edit_user_registration_path %></span>
                <span class="nav_links pull-right"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></span>
              <% else %>
                <span class="nav_links pull-right"><%= link_to 'Sign Up', new_user_registration_path %></span>
                <span class="nav_links pull-right"><%= link_to 'Log In', new_user_session_path %></span>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>  

<%= yield %>

</body>
</html>

app/views/posts/_likes.html.erb
<% if user_signed_in? %>
  <span class="post_like">
    <% if current_user.voted_up_on? post %>
      <%= link_to '<i class="fa fa-heart" aria-hidden="true"></i>'.html_safe, post_downvotes_path(post.id), method: :post, remote: true %> 
    <% else %>
        <%= link_to '<i class="fa fa-heart-o" aria-hidden="true"></i>'.html_safe, post_upvotes_path(post.id), method: :post, remote: true %>
    <% end %>

    <%= pluralize post.get_likes.size, "like" %>
  </span>
<% else %>
  <span class="post_like">
    <i class="fa fa-heart-o" aria-hidden="true"></i> <%= pluralize post.get_likes.size, "like" %>
  </span>
<% end %>
      

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= simple_form_for @post,method: :patch  do |f| %>
  <%= f.input :photo %>
  <%= f.input :description %>
  <%= f.submit 'Update', class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do|post| %>
  <div class="post_box">
    
    <div class="post_header">
    
      <div><%= image_tag post.user_photo,class:'prof_pic_small' %></div> 
      <div><%= link_to post.user_name, user_path(post.user_id) %></div>
      <span class="timestamp pull-right"><%=distance_of_time_in_words(DateTime.now, post.created_at)%>ago</span>
    </div>
    
      
      
    <div class="post_body">
      <%= image_tag post.photo, class:'photo' %>
      <%= link_to 'View Post',post_path(post.id)%>
     
      <%= link_to post.user.name, user_path(post.user_id)%> : <%= post.description %>
       
    
      <% if post.user == current_user %>
        <%= link_to 'Edit Post', edit_post_path(post.id) %>
        <%= link_to 'Delete', post_path(post.id), method: :delete, data: {confirm: "are you sure?"} %>
      <% end %>
    
    
    
    
    
    <div class="post_comments">
      <% post.comments.each do |comment| %>
        <p><%=link_to comment.user_name, user_path(comment.user_id) %> : <%=comment.text %></p>
        <% if comment.user == current_user %>
        <%= link_to 'Delete', post_comments_path(post_id: post.id, id:comment.id), method: :delete %>
        <% end %>
      <% end %>
    
      <hr>
      <span id="likes_container_<%=post.id%>">
        <%= render partial: 'likes',locals: {post: post} %>
      </span>
      
      <% if user_signed_in? %>
        <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post do|f| %>
          <%= f.input  :text,label:"Comment", placeholder:"Add a Comment..." %>
          <%= f.submit 'Submit',class: 'btn btn-primary btn-block' %>
        <% end %>
      <% end %> 
    </div>
    </div>
  </div>
  
<% end %>

app/views/posts/new.html.erb
<%= simple_form_for @post, method: :post do |post| %>
  <%= post.input :photo %>
  <%= post.input :description %>
  <%= post.submit 'Post', class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/show.html.erb
<div class= "prof_header">
  <div class="row">
    <div column="col-xs-4">
        <%= image_tag @post.user.photo, class:'prof-pic' %>
    </div>
    <div class="col-xs-8">
      <div class="user_header">
        <div class="row">
          <div class="col-xs-6">
            <h1 class="username"><%= @post.user.name %></h1>
          </div>
        </div>
      </div>
    </div>
      <div class="prof_post_box">
      <div class="row">
        <%= image_tag @post.photo %></h1>
        <%= @post.description %></h1>
      <div class="col-xs-6">
        <% if @post.user == current_user %>
        <%= link_to 'Edit Post', edit_post_path(@post.id) %>
        <%= link_to 'Delete', post_path(@post.id), method: :delete, data: {confirm: "are you sure?"} %>
        <% end %>
      </div>
      </div>
      </div>
  </div>
</div>

app/views/upvotes/create.js.erb
$('#likes_container_<%=@post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: {post: @post}%>")

app/views/users/show.html.erb
<%= image_tag @user.photo %>
<%= @user.name %>

<%= pluralize (@user.posts.count,'Post')>

<% @user.posts. each do |post| %>
  <%= image_tag post.photo %>
<% end %>